version: "3"
services:
  web:
    build: .
    ports:
      - "5005:5000"
    depends_on:
      - db
  db:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "newfeed-db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "1234"
    ports:
      - "3306:3306"
